In [13]:
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import SGDRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [14]:
data = fetch_california_housing()
df = pd.DataFrame(data.data, columns=data.feature_names)
print(df.head())

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25  


In [15]:
x = data.data[:, :3]
y = np.column_stack((data.target, data.data[:, 6]))
print(x)
print(y)

[[ 8.3252     41.          6.98412698]
 [ 8.3014     21.          6.23813708]
 [ 7.2574     52.          8.28813559]
 ...
 [ 1.7        17.          5.20554273]
 [ 1.8672     18.          5.32951289]
 [ 2.3886     16.          5.25471698]]
[[ 4.526 37.88 ]
 [ 3.585 37.86 ]
 [ 3.521 37.85 ]
 ...
 [ 0.923 39.43 ]
 [ 0.847 39.43 ]
 [ 0.894 39.37 ]]


In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
scaler_x = StandardScaler()
scaler_y = StandardScaler()

In [17]:
x_train = scaler_x.fit_transform(x_train)
x_test = scaler_x.transform(x_test)
y_train = scaler_y.fit_transform(y_train)
y_test = scaler_y.transform(y_test)

In [19]:
sgd = SGDRegressor(max_iter=1000, tol=1e-3)
multi_output_sgd = MultiOutputRegressor(sgd)
multi_output_sgd.fit(x_train, y_train)
y_pred = multi_output_sgd.predict(x_test)

In [20]:
y_pred = scaler_y.inverse_transform(y_pred)
y_test = scaler_y.inverse_transform(y_test)

In [ ]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 2.5791397555623794


In [22]:
print("\nPredictions:\n", y_pred[:5])


Predictions:
 [[ 1.865597   35.81397196]
 [ 4.36496414 35.17325573]
 [ 1.28898869 35.82496905]
 [ 1.41329183 35.70818278]
 [ 2.52491452 35.64193145]]
